# Generated by Django 5.1.3 on 2024-11-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_episode_description_alter_episode_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
